/// Flutter icons DigitalContractIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DigitalContractIcons
///      fonts:
///       - asset: fonts/DigitalContractIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DigitalContractIcons {
  DigitalContractIcons._();

  static const _kFontFam = 'DigitalContractIcons';
  static const String? _kFontPkg = null;

  static const IconData arrow_rotate_right_solid = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bath_solid = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bed_solid = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_slash_solid = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_regular = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_solid = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_regular = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_solid = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData building_user_solid = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_days_regular = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_days_solid = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_regular = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_solid = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_solid = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_solid = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_check_regular = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_check_solid = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_down_regular = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_down_solid = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_plus_solid = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_question_regular = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_xmark_regular = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_xmark_solid = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData city_solid = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_regular = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_solid = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comments_regular = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comments_solid = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy_solid = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card_regular = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card_solid = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollar_sign_solid = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download_solid = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData earth_americas_solid = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eraser_solid = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData faucet_drip_solid = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_circle_check_solid = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_image_solid = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_invoice_dollar_solid = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_invoice_solid = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_lines_regular = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_pdf_regular = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_pdf_solid = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_signature_solid = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_open_regular = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData handshake_angle_solid = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData handshake_regular = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData handshake_solid = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_regular = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_solid = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData house_solid = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image_regular = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image_solid = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key_solid = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lightbulb_regular = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lightbulb_solid = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link_solid = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_dot_solid = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magnifying_glass_solid = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_location_dot_solid = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mars_solid = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus_solid = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_bill_wave_solid = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_bills_solid = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nfc_directional = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane_regular = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paw_solid = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_solid = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_solid = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qrcode_solid = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question_solid = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_nodes_solid = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_solid = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signature_solid = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData square_parking_solid = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_solid = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_check_solid = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_regular = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_solid = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData venus_solid = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wifi_solid = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData xmark_solid = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_info_solid = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_solid = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
